/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AvailableGroupMembersAllOf from './AvailableGroupMembersAllOf';

/**
 * The AvailableGroupMembers model module.
 * @module model/AvailableGroupMembers
 * @version 1.0.0
 */
class AvailableGroupMembers {
    /**
     * Constructs a new <code>AvailableGroupMembers</code>.
     * Represents a group Members definition.
     * @alias module:model/AvailableGroupMembers
     * @implements module:model/AvailableGroupMembersAllOf
     */
    constructor() { 
        AvailableGroupMembersAllOf.initialize(this);
        AvailableGroupMembers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailableGroupMembers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailableGroupMembers} obj Optional instance to populate.
     * @return {module:model/AvailableGroupMembers} The populated <code>AvailableGroupMembers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailableGroupMembers();
            AvailableGroupMembersAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AvailableGroupMembers.prototype['id'] = undefined;

/**
 * @member {String} description
 */
AvailableGroupMembers.prototype['description'] = undefined;

/**
 * @member {String} name
 */
AvailableGroupMembers.prototype['name'] = undefined;

/**
 * @member {module:model/AvailableGroupMembers.StatusEnum} status
 */
AvailableGroupMembers.prototype['status'] = undefined;

/**
 * @member {Date} created_at
 */
AvailableGroupMembers.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
AvailableGroupMembers.prototype['updated_at'] = undefined;


// Implement AvailableGroupMembersAllOf interface:
/**
 * @member {String} id
 */
AvailableGroupMembersAllOf.prototype['id'] = undefined;
/**
 * @member {String} description
 */
AvailableGroupMembersAllOf.prototype['description'] = undefined;
/**
 * @member {String} name
 */
AvailableGroupMembersAllOf.prototype['name'] = undefined;
/**
 * @member {module:model/AvailableGroupMembersAllOf.StatusEnum} status
 */
AvailableGroupMembersAllOf.prototype['status'] = undefined;
/**
 * @member {Date} created_at
 */
AvailableGroupMembersAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
AvailableGroupMembersAllOf.prototype['updated_at'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
AvailableGroupMembers['StatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "INACTIVE"
     * @const
     */
    "INACTIVE": "INACTIVE"
};



export default AvailableGroupMembers;

