/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AvailableLanguages model module.
 * @module model/AvailableLanguages
 * @version 1.0.0
 */
class AvailableLanguages {
    /**
     * Constructs a new <code>AvailableLanguages</code>.
     * Represents an Eloquent model of a Script Executor
     * @alias module:model/AvailableLanguages
     */
    constructor() { 
        
        AvailableLanguages.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AvailableLanguages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvailableLanguages} obj Optional instance to populate.
     * @return {module:model/AvailableLanguages} The populated <code>AvailableLanguages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvailableLanguages();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('initDockerFile')) {
                obj['initDockerFile'] = ApiClient.convertToType(data['initDockerFile'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
AvailableLanguages.prototype['text'] = undefined;

/**
 * @member {String} value
 */
AvailableLanguages.prototype['value'] = undefined;

/**
 * @member {String} initDockerFile
 */
AvailableLanguages.prototype['initDockerFile'] = undefined;






export default AvailableLanguages;

