/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetGroupMembersByIdAllOf model module.
 * @module model/GetGroupMembersByIdAllOf
 * @version 1.0.0
 */
class GetGroupMembersByIdAllOf {
    /**
     * Constructs a new <code>GetGroupMembersByIdAllOf</code>.
     * @alias module:model/GetGroupMembersByIdAllOf
     */
    constructor() { 
        
        GetGroupMembersByIdAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetGroupMembersByIdAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetGroupMembersByIdAllOf} obj Optional instance to populate.
     * @return {module:model/GetGroupMembersByIdAllOf} The populated <code>GetGroupMembersByIdAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetGroupMembersByIdAllOf();

            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
            if (data.hasOwnProperty('member_id')) {
                obj['member_id'] = ApiClient.convertToType(data['member_id'], 'String');
            }
            if (data.hasOwnProperty('member_type')) {
                obj['member_type'] = ApiClient.convertToType(data['member_type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} group_id
 */
GetGroupMembersByIdAllOf.prototype['group_id'] = undefined;

/**
 * @member {String} member_id
 */
GetGroupMembersByIdAllOf.prototype['member_id'] = undefined;

/**
 * @member {String} member_type
 */
GetGroupMembersByIdAllOf.prototype['member_type'] = undefined;

/**
 * @member {String} id
 */
GetGroupMembersByIdAllOf.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
GetGroupMembersByIdAllOf.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
GetGroupMembersByIdAllOf.prototype['updated_at'] = undefined;






export default GetGroupMembersByIdAllOf;

