/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MediaEditable model module.
 * @module model/MediaEditable
 * @version 1.0.0
 */
class MediaEditable {
    /**
     * Constructs a new <code>MediaEditable</code>.
     * @alias module:model/MediaEditable
     */
    constructor() { 
        
        MediaEditable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaEditable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaEditable} obj Optional instance to populate.
     * @return {module:model/MediaEditable} The populated <code>MediaEditable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaEditable();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('model_id')) {
                obj['model_id'] = ApiClient.convertToType(data['model_id'], 'Number');
            }
            if (data.hasOwnProperty('model_type')) {
                obj['model_type'] = ApiClient.convertToType(data['model_type'], 'String');
            }
            if (data.hasOwnProperty('collection_name')) {
                obj['collection_name'] = ApiClient.convertToType(data['collection_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('mime_type')) {
                obj['mime_type'] = ApiClient.convertToType(data['mime_type'], 'String');
            }
            if (data.hasOwnProperty('disk')) {
                obj['disk'] = ApiClient.convertToType(data['disk'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('manipulations')) {
                obj['manipulations'] = ApiClient.convertToType(data['manipulations'], Object);
            }
            if (data.hasOwnProperty('custom_properties')) {
                obj['custom_properties'] = ApiClient.convertToType(data['custom_properties'], Object);
            }
            if (data.hasOwnProperty('responsive_images')) {
                obj['responsive_images'] = ApiClient.convertToType(data['responsive_images'], Object);
            }
            if (data.hasOwnProperty('order_column')) {
                obj['order_column'] = ApiClient.convertToType(data['order_column'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MediaEditable.prototype['id'] = undefined;

/**
 * @member {Number} model_id
 */
MediaEditable.prototype['model_id'] = undefined;

/**
 * @member {String} model_type
 */
MediaEditable.prototype['model_type'] = undefined;

/**
 * @member {String} collection_name
 */
MediaEditable.prototype['collection_name'] = undefined;

/**
 * @member {String} name
 */
MediaEditable.prototype['name'] = undefined;

/**
 * @member {String} file_name
 */
MediaEditable.prototype['file_name'] = undefined;

/**
 * @member {String} mime_type
 */
MediaEditable.prototype['mime_type'] = undefined;

/**
 * @member {String} disk
 */
MediaEditable.prototype['disk'] = undefined;

/**
 * @member {Number} size
 */
MediaEditable.prototype['size'] = undefined;

/**
 * @member {Object} manipulations
 */
MediaEditable.prototype['manipulations'] = undefined;

/**
 * @member {Object} custom_properties
 */
MediaEditable.prototype['custom_properties'] = undefined;

/**
 * @member {Object} responsive_images
 */
MediaEditable.prototype['responsive_images'] = undefined;

/**
 * @member {Number} order_column
 */
MediaEditable.prototype['order_column'] = undefined;






export default MediaEditable;

