/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NotificationAllOf from './NotificationAllOf';
import NotificationEditable from './NotificationEditable';

/**
 * The Notification model module.
 * @module model/Notification
 * @version 1.0.0
 */
class Notification {
    /**
     * Constructs a new <code>Notification</code>.
     * Represents a notification definition.
     * @alias module:model/Notification
     * @implements module:model/NotificationAllOf
     * @implements module:model/NotificationEditable
     */
    constructor() { 
        NotificationAllOf.initialize(this);NotificationEditable.initialize(this);
        Notification.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Notification} obj Optional instance to populate.
     * @return {module:model/Notification} The populated <code>Notification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Notification();
            NotificationAllOf.constructFromObject(data, obj);
            NotificationEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('read_at')) {
                obj['read_at'] = ApiClient.convertToType(data['read_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('notifiable_type')) {
                obj['notifiable_type'] = ApiClient.convertToType(data['notifiable_type'], 'String');
            }
            if (data.hasOwnProperty('notifiable_id')) {
                obj['notifiable_id'] = ApiClient.convertToType(data['notifiable_id'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('processName')) {
                obj['processName'] = ApiClient.convertToType(data['processName'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Notification.prototype['id'] = undefined;

/**
 * @member {Date} read_at
 */
Notification.prototype['read_at'] = undefined;

/**
 * @member {Date} created_at
 */
Notification.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Notification.prototype['updated_at'] = undefined;

/**
 * @member {String} type
 */
Notification.prototype['type'] = undefined;

/**
 * @member {String} notifiable_type
 */
Notification.prototype['notifiable_type'] = undefined;

/**
 * @member {Number} notifiable_id
 */
Notification.prototype['notifiable_id'] = undefined;

/**
 * @member {String} data
 */
Notification.prototype['data'] = undefined;

/**
 * @member {String} name
 */
Notification.prototype['name'] = undefined;

/**
 * @member {String} message
 */
Notification.prototype['message'] = undefined;

/**
 * @member {String} processName
 */
Notification.prototype['processName'] = undefined;

/**
 * @member {String} userName
 */
Notification.prototype['userName'] = undefined;

/**
 * @member {String} request_id
 */
Notification.prototype['request_id'] = undefined;


// Implement NotificationAllOf interface:
/**
 * @member {String} id
 */
NotificationAllOf.prototype['id'] = undefined;
/**
 * @member {Date} read_at
 */
NotificationAllOf.prototype['read_at'] = undefined;
/**
 * @member {Date} created_at
 */
NotificationAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
NotificationAllOf.prototype['updated_at'] = undefined;
// Implement NotificationEditable interface:
/**
 * @member {String} type
 */
NotificationEditable.prototype['type'] = undefined;
/**
 * @member {String} notifiable_type
 */
NotificationEditable.prototype['notifiable_type'] = undefined;
/**
 * @member {Number} notifiable_id
 */
NotificationEditable.prototype['notifiable_id'] = undefined;
/**
 * @member {String} data
 */
NotificationEditable.prototype['data'] = undefined;
/**
 * @member {String} name
 */
NotificationEditable.prototype['name'] = undefined;
/**
 * @member {String} message
 */
NotificationEditable.prototype['message'] = undefined;
/**
 * @member {String} processName
 */
NotificationEditable.prototype['processName'] = undefined;
/**
 * @member {String} userName
 */
NotificationEditable.prototype['userName'] = undefined;
/**
 * @member {String} request_id
 */
NotificationEditable.prototype['request_id'] = undefined;




export default Notification;

