/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NotificationAllOf model module.
 * @module model/NotificationAllOf
 * @version 1.0.0
 */
class NotificationAllOf {
    /**
     * Constructs a new <code>NotificationAllOf</code>.
     * @alias module:model/NotificationAllOf
     */
    constructor() { 
        
        NotificationAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NotificationAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotificationAllOf} obj Optional instance to populate.
     * @return {module:model/NotificationAllOf} The populated <code>NotificationAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationAllOf();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('read_at')) {
                obj['read_at'] = ApiClient.convertToType(data['read_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
NotificationAllOf.prototype['id'] = undefined;

/**
 * @member {Date} read_at
 */
NotificationAllOf.prototype['read_at'] = undefined;

/**
 * @member {Date} created_at
 */
NotificationAllOf.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
NotificationAllOf.prototype['updated_at'] = undefined;






export default NotificationAllOf;

