/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessStartEvents from './ProcessStartEvents';

/**
 * The ProcessWithStartEventsAllOf model module.
 * @module model/ProcessWithStartEventsAllOf
 * @version 1.0.0
 */
class ProcessWithStartEventsAllOf {
    /**
     * Constructs a new <code>ProcessWithStartEventsAllOf</code>.
     * @alias module:model/ProcessWithStartEventsAllOf
     */
    constructor() { 
        
        ProcessWithStartEventsAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessWithStartEventsAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessWithStartEventsAllOf} obj Optional instance to populate.
     * @return {module:model/ProcessWithStartEventsAllOf} The populated <code>ProcessWithStartEventsAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessWithStartEventsAllOf();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [ProcessStartEvents]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ProcessStartEvents>} events
 */
ProcessWithStartEventsAllOf.prototype['events'] = undefined;






export default ProcessWithStartEventsAllOf;

