/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProcessAllOf model module.
 * @module model/ProcessAllOf
 * @version 1.0.0
 */
class ProcessAllOf {
    /**
     * Constructs a new <code>ProcessAllOf</code>.
     * @alias module:model/ProcessAllOf
     */
    constructor() { 
        
        ProcessAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessAllOf} obj Optional instance to populate.
     * @return {module:model/ProcessAllOf} The populated <code>ProcessAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessAllOf();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], Object);
            }
            if (data.hasOwnProperty('task_notifications')) {
                obj['task_notifications'] = ApiClient.convertToType(data['task_notifications'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} user_id
 */
ProcessAllOf.prototype['user_id'] = undefined;

/**
 * @member {String} id
 */
ProcessAllOf.prototype['id'] = undefined;

/**
 * @member {Date} deleted_at
 */
ProcessAllOf.prototype['deleted_at'] = undefined;

/**
 * @member {Date} created_at
 */
ProcessAllOf.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ProcessAllOf.prototype['updated_at'] = undefined;

/**
 * @member {Object} notifications
 */
ProcessAllOf.prototype['notifications'] = undefined;

/**
 * @member {Object} task_notifications
 */
ProcessAllOf.prototype['task_notifications'] = undefined;






export default ProcessAllOf;

