/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProcessRequestTokenEditable model module.
 * @module model/ProcessRequestTokenEditable
 * @version 1.0.0
 */
class ProcessRequestTokenEditable {
    /**
     * Constructs a new <code>ProcessRequestTokenEditable</code>.
     * @alias module:model/ProcessRequestTokenEditable
     */
    constructor() { 
        
        ProcessRequestTokenEditable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessRequestTokenEditable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessRequestTokenEditable} obj Optional instance to populate.
     * @return {module:model/ProcessRequestTokenEditable} The populated <code>ProcessRequestTokenEditable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessRequestTokenEditable();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('due_at')) {
                obj['due_at'] = ApiClient.convertToType(data['due_at'], 'Date');
            }
            if (data.hasOwnProperty('initiated_at')) {
                obj['initiated_at'] = ApiClient.convertToType(data['initiated_at'], 'Date');
            }
            if (data.hasOwnProperty('riskchanges_at')) {
                obj['riskchanges_at'] = ApiClient.convertToType(data['riskchanges_at'], 'Date');
            }
            if (data.hasOwnProperty('subprocess_start_event_id')) {
                obj['subprocess_start_event_id'] = ApiClient.convertToType(data['subprocess_start_event_id'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} user_id
 */
ProcessRequestTokenEditable.prototype['user_id'] = undefined;

/**
 * @member {String} status
 */
ProcessRequestTokenEditable.prototype['status'] = undefined;

/**
 * @member {Date} due_at
 */
ProcessRequestTokenEditable.prototype['due_at'] = undefined;

/**
 * @member {Date} initiated_at
 */
ProcessRequestTokenEditable.prototype['initiated_at'] = undefined;

/**
 * @member {Date} riskchanges_at
 */
ProcessRequestTokenEditable.prototype['riskchanges_at'] = undefined;

/**
 * @member {String} subprocess_start_event_id
 */
ProcessRequestTokenEditable.prototype['subprocess_start_event_id'] = undefined;

/**
 * @member {Object} data
 */
ProcessRequestTokenEditable.prototype['data'] = undefined;






export default ProcessRequestTokenEditable;

