/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessAllOf from './ProcessAllOf';
import ProcessEditable from './ProcessEditable';
import ProcessStartEvents from './ProcessStartEvents';

/**
 * The Process model module.
 * @module model/Process
 * @version 1.0.0
 */
class Process {
    /**
     * Constructs a new <code>Process</code>.
     * @alias module:model/Process
     * @implements module:model/ProcessAllOf
     * @implements module:model/ProcessEditable
     */
    constructor() { 
        ProcessAllOf.initialize(this);ProcessEditable.initialize(this);
        Process.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Process</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Process} obj Optional instance to populate.
     * @return {module:model/Process} The populated <code>Process</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Process();
            ProcessAllOf.constructFromObject(data, obj);
            ProcessEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], Object);
            }
            if (data.hasOwnProperty('task_notifications')) {
                obj['task_notifications'] = ApiClient.convertToType(data['task_notifications'], Object);
            }
            if (data.hasOwnProperty('process_category_id')) {
                obj['process_category_id'] = ApiClient.convertToType(data['process_category_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('pause_timer_start')) {
                obj['pause_timer_start'] = ApiClient.convertToType(data['pause_timer_start'], 'Number');
            }
            if (data.hasOwnProperty('cancel_screen_id')) {
                obj['cancel_screen_id'] = ApiClient.convertToType(data['cancel_screen_id'], 'Number');
            }
            if (data.hasOwnProperty('has_timer_start_events')) {
                obj['has_timer_start_events'] = ApiClient.convertToType(data['has_timer_start_events'], 'Boolean');
            }
            if (data.hasOwnProperty('request_detail_screen_id')) {
                obj['request_detail_screen_id'] = ApiClient.convertToType(data['request_detail_screen_id'], 'Number');
            }
            if (data.hasOwnProperty('is_valid')) {
                obj['is_valid'] = ApiClient.convertToType(data['is_valid'], 'Number');
            }
            if (data.hasOwnProperty('package_key')) {
                obj['package_key'] = ApiClient.convertToType(data['package_key'], 'String');
            }
            if (data.hasOwnProperty('start_events')) {
                obj['start_events'] = ApiClient.convertToType(data['start_events'], [ProcessStartEvents]);
            }
            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], 'String');
            }
            if (data.hasOwnProperty('self_service_tasks')) {
                obj['self_service_tasks'] = ApiClient.convertToType(data['self_service_tasks'], Object);
            }
            if (data.hasOwnProperty('signal_events')) {
                obj['signal_events'] = ApiClient.convertToType(data['signal_events'], [Object]);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], Object);
            }
            if (data.hasOwnProperty('manager_id')) {
                obj['manager_id'] = ApiClient.convertToType(data['manager_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} user_id
 */
Process.prototype['user_id'] = undefined;

/**
 * @member {String} id
 */
Process.prototype['id'] = undefined;

/**
 * @member {Date} deleted_at
 */
Process.prototype['deleted_at'] = undefined;

/**
 * @member {Date} created_at
 */
Process.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Process.prototype['updated_at'] = undefined;

/**
 * @member {Object} notifications
 */
Process.prototype['notifications'] = undefined;

/**
 * @member {Object} task_notifications
 */
Process.prototype['task_notifications'] = undefined;

/**
 * @member {Number} process_category_id
 */
Process.prototype['process_category_id'] = undefined;

/**
 * @member {String} name
 */
Process.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Process.prototype['description'] = undefined;

/**
 * @member {module:model/Process.StatusEnum} status
 */
Process.prototype['status'] = undefined;

/**
 * @member {Number} pause_timer_start
 */
Process.prototype['pause_timer_start'] = undefined;

/**
 * @member {Number} cancel_screen_id
 */
Process.prototype['cancel_screen_id'] = undefined;

/**
 * @member {Boolean} has_timer_start_events
 */
Process.prototype['has_timer_start_events'] = undefined;

/**
 * @member {Number} request_detail_screen_id
 */
Process.prototype['request_detail_screen_id'] = undefined;

/**
 * @member {Number} is_valid
 */
Process.prototype['is_valid'] = undefined;

/**
 * @member {String} package_key
 */
Process.prototype['package_key'] = undefined;

/**
 * @member {Array.<module:model/ProcessStartEvents>} start_events
 */
Process.prototype['start_events'] = undefined;

/**
 * @member {String} warnings
 */
Process.prototype['warnings'] = undefined;

/**
 * @member {Object} self_service_tasks
 */
Process.prototype['self_service_tasks'] = undefined;

/**
 * @member {Array.<Object>} signal_events
 */
Process.prototype['signal_events'] = undefined;

/**
 * @member {Object} category
 */
Process.prototype['category'] = undefined;

/**
 * @member {Number} manager_id
 */
Process.prototype['manager_id'] = undefined;


// Implement ProcessAllOf interface:
/**
 * @member {Number} user_id
 */
ProcessAllOf.prototype['user_id'] = undefined;
/**
 * @member {String} id
 */
ProcessAllOf.prototype['id'] = undefined;
/**
 * @member {Date} deleted_at
 */
ProcessAllOf.prototype['deleted_at'] = undefined;
/**
 * @member {Date} created_at
 */
ProcessAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
ProcessAllOf.prototype['updated_at'] = undefined;
/**
 * @member {Object} notifications
 */
ProcessAllOf.prototype['notifications'] = undefined;
/**
 * @member {Object} task_notifications
 */
ProcessAllOf.prototype['task_notifications'] = undefined;
// Implement ProcessEditable interface:
/**
 * @member {Number} process_category_id
 */
ProcessEditable.prototype['process_category_id'] = undefined;
/**
 * @member {String} name
 */
ProcessEditable.prototype['name'] = undefined;
/**
 * @member {String} description
 */
ProcessEditable.prototype['description'] = undefined;
/**
 * @member {module:model/ProcessEditable.StatusEnum} status
 */
ProcessEditable.prototype['status'] = undefined;
/**
 * @member {Number} pause_timer_start
 */
ProcessEditable.prototype['pause_timer_start'] = undefined;
/**
 * @member {Number} cancel_screen_id
 */
ProcessEditable.prototype['cancel_screen_id'] = undefined;
/**
 * @member {Boolean} has_timer_start_events
 */
ProcessEditable.prototype['has_timer_start_events'] = undefined;
/**
 * @member {Number} request_detail_screen_id
 */
ProcessEditable.prototype['request_detail_screen_id'] = undefined;
/**
 * @member {Number} is_valid
 */
ProcessEditable.prototype['is_valid'] = undefined;
/**
 * @member {String} package_key
 */
ProcessEditable.prototype['package_key'] = undefined;
/**
 * @member {Array.<module:model/ProcessStartEvents>} start_events
 */
ProcessEditable.prototype['start_events'] = undefined;
/**
 * @member {String} warnings
 */
ProcessEditable.prototype['warnings'] = undefined;
/**
 * @member {Object} self_service_tasks
 */
ProcessEditable.prototype['self_service_tasks'] = undefined;
/**
 * @member {Array.<Object>} signal_events
 */
ProcessEditable.prototype['signal_events'] = undefined;
/**
 * @member {Object} category
 */
ProcessEditable.prototype['category'] = undefined;
/**
 * @member {Number} manager_id
 */
ProcessEditable.prototype['manager_id'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Process['StatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "INACTIVE"
     * @const
     */
    "INACTIVE": "INACTIVE",

    /**
     * value: "ARCHIVED"
     * @const
     */
    "ARCHIVED": "ARCHIVED"
};



export default Process;

