/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProcessAssignments model module.
 * @module model/ProcessAssignments
 * @version 1.0.0
 */
class ProcessAssignments {
    /**
     * Constructs a new <code>ProcessAssignments</code>.
     * Represents a business process definition.
     * @alias module:model/ProcessAssignments
     */
    constructor() { 
        
        ProcessAssignments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessAssignments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessAssignments} obj Optional instance to populate.
     * @return {module:model/ProcessAssignments} The populated <code>ProcessAssignments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessAssignments();

            if (data.hasOwnProperty('assignable')) {
                obj['assignable'] = ApiClient.convertToType(data['assignable'], [Object]);
            }
            if (data.hasOwnProperty('cancel_request')) {
                obj['cancel_request'] = ApiClient.convertToType(data['cancel_request'], Object);
            }
            if (data.hasOwnProperty('edit_data')) {
                obj['edit_data'] = ApiClient.convertToType(data['edit_data'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} assignable
 */
ProcessAssignments.prototype['assignable'] = undefined;

/**
 * @member {Object} cancel_request
 */
ProcessAssignments.prototype['cancel_request'] = undefined;

/**
 * @member {Object} edit_data
 */
ProcessAssignments.prototype['edit_data'] = undefined;






export default ProcessAssignments;

