/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnvironmentVariableAllOf from './EnvironmentVariableAllOf';
import ScriptsEditable from './ScriptsEditable';

/**
 * The Scripts model module.
 * @module model/Scripts
 * @version 1.0.0
 */
class Scripts {
    /**
     * Constructs a new <code>Scripts</code>.
     * @alias module:model/Scripts
     * @implements module:model/EnvironmentVariableAllOf
     * @implements module:model/ScriptsEditable
     */
    constructor() { 
        EnvironmentVariableAllOf.initialize(this);ScriptsEditable.initialize(this);
        Scripts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Scripts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Scripts} obj Optional instance to populate.
     * @return {module:model/Scripts} The populated <code>Scripts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Scripts();
            EnvironmentVariableAllOf.constructFromObject(data, obj);
            ScriptsEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
            }
            if (data.hasOwnProperty('run_as_user_id')) {
                obj['run_as_user_id'] = ApiClient.convertToType(data['run_as_user_id'], 'Number');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('script_category_id')) {
                obj['script_category_id'] = ApiClient.convertToType(data['script_category_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Scripts.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Scripts.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Scripts.prototype['updated_at'] = undefined;

/**
 * @member {String} title
 */
Scripts.prototype['title'] = undefined;

/**
 * @member {String} description
 */
Scripts.prototype['description'] = undefined;

/**
 * @member {String} language
 */
Scripts.prototype['language'] = undefined;

/**
 * @member {String} code
 */
Scripts.prototype['code'] = undefined;

/**
 * @member {Number} timeout
 */
Scripts.prototype['timeout'] = undefined;

/**
 * @member {Number} run_as_user_id
 */
Scripts.prototype['run_as_user_id'] = undefined;

/**
 * @member {String} key
 */
Scripts.prototype['key'] = undefined;

/**
 * @member {Number} script_category_id
 */
Scripts.prototype['script_category_id'] = undefined;


// Implement EnvironmentVariableAllOf interface:
/**
 * @member {Number} id
 */
EnvironmentVariableAllOf.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
EnvironmentVariableAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
EnvironmentVariableAllOf.prototype['updated_at'] = undefined;
// Implement ScriptsEditable interface:
/**
 * @member {String} title
 */
ScriptsEditable.prototype['title'] = undefined;
/**
 * @member {String} description
 */
ScriptsEditable.prototype['description'] = undefined;
/**
 * @member {String} language
 */
ScriptsEditable.prototype['language'] = undefined;
/**
 * @member {String} code
 */
ScriptsEditable.prototype['code'] = undefined;
/**
 * @member {Number} timeout
 */
ScriptsEditable.prototype['timeout'] = undefined;
/**
 * @member {Number} run_as_user_id
 */
ScriptsEditable.prototype['run_as_user_id'] = undefined;
/**
 * @member {String} key
 */
ScriptsEditable.prototype['key'] = undefined;
/**
 * @member {Number} script_category_id
 */
ScriptsEditable.prototype['script_category_id'] = undefined;




export default Scripts;

