/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnvironmentVariableAllOf from './EnvironmentVariableAllOf';
import ScriptExecutorsEditable from './ScriptExecutorsEditable';

/**
 * The ScriptExecutors model module.
 * @module model/ScriptExecutors
 * @version 1.0.0
 */
class ScriptExecutors {
    /**
     * Constructs a new <code>ScriptExecutors</code>.
     * @alias module:model/ScriptExecutors
     * @implements module:model/EnvironmentVariableAllOf
     * @implements module:model/ScriptExecutorsEditable
     */
    constructor() { 
        EnvironmentVariableAllOf.initialize(this);ScriptExecutorsEditable.initialize(this);
        ScriptExecutors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScriptExecutors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScriptExecutors} obj Optional instance to populate.
     * @return {module:model/ScriptExecutors} The populated <code>ScriptExecutors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScriptExecutors();
            EnvironmentVariableAllOf.constructFromObject(data, obj);
            ScriptExecutorsEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ScriptExecutors.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
ScriptExecutors.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ScriptExecutors.prototype['updated_at'] = undefined;

/**
 * @member {String} title
 */
ScriptExecutors.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ScriptExecutors.prototype['description'] = undefined;

/**
 * @member {String} language
 */
ScriptExecutors.prototype['language'] = undefined;

/**
 * @member {String} config
 */
ScriptExecutors.prototype['config'] = undefined;


// Implement EnvironmentVariableAllOf interface:
/**
 * @member {Number} id
 */
EnvironmentVariableAllOf.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
EnvironmentVariableAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
EnvironmentVariableAllOf.prototype['updated_at'] = undefined;
// Implement ScriptExecutorsEditable interface:
/**
 * @member {String} title
 */
ScriptExecutorsEditable.prototype['title'] = undefined;
/**
 * @member {String} description
 */
ScriptExecutorsEditable.prototype['description'] = undefined;
/**
 * @member {String} language
 */
ScriptExecutorsEditable.prototype['language'] = undefined;
/**
 * @member {String} config
 */
ScriptExecutorsEditable.prototype['config'] = undefined;




export default ScriptExecutors;

