/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScriptsPreview model module.
 * @module model/ScriptsPreview
 * @version 1.0.0
 */
class ScriptsPreview {
    /**
     * Constructs a new <code>ScriptsPreview</code>.
     * Represents an Eloquent model of a Script
     * @alias module:model/ScriptsPreview
     */
    constructor() { 
        
        ScriptsPreview.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScriptsPreview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScriptsPreview} obj Optional instance to populate.
     * @return {module:model/ScriptsPreview} The populated <code>ScriptsPreview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScriptsPreview();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} status
 */
ScriptsPreview.prototype['status'] = undefined;

/**
 * @member {String} key
 */
ScriptsPreview.prototype['key'] = undefined;






export default ScriptsPreview;

