/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SecurityLogMeta from './SecurityLogMeta';

/**
 * The SecurityLog model module.
 * @module model/SecurityLog
 * @version 1.0.0
 */
class SecurityLog {
    /**
     * Constructs a new <code>SecurityLog</code>.
     * Class SecurityLog
     * @alias module:model/SecurityLog
     */
    constructor() { 
        
        SecurityLog.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecurityLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecurityLog} obj Optional instance to populate.
     * @return {module:model/SecurityLog} The populated <code>SecurityLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecurityLog();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], [SecurityLogMeta]);
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('occured_at')) {
                obj['occured_at'] = ApiClient.convertToType(data['occured_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SecurityLog.prototype['id'] = undefined;

/**
 * @member {String} event
 */
SecurityLog.prototype['event'] = undefined;

/**
 * @member {String} ip
 */
SecurityLog.prototype['ip'] = undefined;

/**
 * @member {Array.<module:model/SecurityLogMeta>} meta
 */
SecurityLog.prototype['meta'] = undefined;

/**
 * @member {Number} user_id
 */
SecurityLog.prototype['user_id'] = undefined;

/**
 * @member {String} occured_at
 */
SecurityLog.prototype['occured_at'] = undefined;






export default SecurityLog;

