/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GroupMembersAllOf from './GroupMembersAllOf';
import SettingsEditable from './SettingsEditable';

/**
 * The Settings model module.
 * @module model/Settings
 * @version 1.0.0
 */
class Settings {
    /**
     * Constructs a new <code>Settings</code>.
     * Class Settings
     * @alias module:model/Settings
     * @implements module:model/GroupMembersAllOf
     * @implements module:model/SettingsEditable
     */
    constructor() { 
        GroupMembersAllOf.initialize(this);SettingsEditable.initialize(this);
        Settings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Settings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Settings} obj Optional instance to populate.
     * @return {module:model/Settings} The populated <code>Settings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Settings();
            GroupMembersAllOf.constructFromObject(data, obj);
            SettingsEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], [Object]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('helper')) {
                obj['helper'] = ApiClient.convertToType(data['helper'], 'String');
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('hidden')) {
                obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
            }
            if (data.hasOwnProperty('readonly')) {
                obj['readonly'] = ApiClient.convertToType(data['readonly'], 'Boolean');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], 'String');
            }
            if (data.hasOwnProperty('sansSerifFont')) {
                obj['sansSerifFont'] = ApiClient.convertToType(data['sansSerifFont'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Settings.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Settings.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Settings.prototype['updated_at'] = undefined;

/**
 * @member {String} key
 */
Settings.prototype['key'] = undefined;

/**
 * @member {Array.<Object>} config
 */
Settings.prototype['config'] = undefined;

/**
 * @member {String} name
 */
Settings.prototype['name'] = undefined;

/**
 * @member {String} helper
 */
Settings.prototype['helper'] = undefined;

/**
 * @member {String} group
 */
Settings.prototype['group'] = undefined;

/**
 * @member {String} format
 */
Settings.prototype['format'] = undefined;

/**
 * @member {Boolean} hidden
 */
Settings.prototype['hidden'] = undefined;

/**
 * @member {Boolean} readonly
 */
Settings.prototype['readonly'] = undefined;

/**
 * @member {String} variables
 */
Settings.prototype['variables'] = undefined;

/**
 * @member {String} sansSerifFont
 */
Settings.prototype['sansSerifFont'] = undefined;


// Implement GroupMembersAllOf interface:
/**
 * @member {String} id
 */
GroupMembersAllOf.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
GroupMembersAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
GroupMembersAllOf.prototype['updated_at'] = undefined;
// Implement SettingsEditable interface:
/**
 * @member {String} key
 */
SettingsEditable.prototype['key'] = undefined;
/**
 * @member {Array.<Object>} config
 */
SettingsEditable.prototype['config'] = undefined;
/**
 * @member {String} name
 */
SettingsEditable.prototype['name'] = undefined;
/**
 * @member {String} helper
 */
SettingsEditable.prototype['helper'] = undefined;
/**
 * @member {String} group
 */
SettingsEditable.prototype['group'] = undefined;
/**
 * @member {String} format
 */
SettingsEditable.prototype['format'] = undefined;
/**
 * @member {Boolean} hidden
 */
SettingsEditable.prototype['hidden'] = undefined;
/**
 * @member {Boolean} readonly
 */
SettingsEditable.prototype['readonly'] = undefined;
/**
 * @member {String} variables
 */
SettingsEditable.prototype['variables'] = undefined;
/**
 * @member {String} sansSerifFont
 */
SettingsEditable.prototype['sansSerifFont'] = undefined;




export default Settings;

