/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SignalsAllOfProcesses from './SignalsAllOfProcesses';

/**
 * The SignalsAllOf model module.
 * @module model/SignalsAllOf
 * @version 1.0.0
 */
class SignalsAllOf {
    /**
     * Constructs a new <code>SignalsAllOf</code>.
     * @alias module:model/SignalsAllOf
     */
    constructor() { 
        
        SignalsAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignalsAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignalsAllOf} obj Optional instance to populate.
     * @return {module:model/SignalsAllOf} The populated <code>SignalsAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignalsAllOf();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('processes')) {
                obj['processes'] = ApiClient.convertToType(data['processes'], [SignalsAllOfProcesses]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
SignalsAllOf.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/SignalsAllOfProcesses>} processes
 */
SignalsAllOf.prototype['processes'] = undefined;






export default SignalsAllOf;

