/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignalsAllOfCatches model module.
 * @module model/SignalsAllOfCatches
 * @version 1.0.0
 */
class SignalsAllOfCatches {
    /**
     * Constructs a new <code>SignalsAllOfCatches</code>.
     * @alias module:model/SignalsAllOfCatches
     */
    constructor() { 
        
        SignalsAllOfCatches.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SignalsAllOfCatches</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignalsAllOfCatches} obj Optional instance to populate.
     * @return {module:model/SignalsAllOfCatches} The populated <code>SignalsAllOfCatches</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignalsAllOfCatches();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SignalsAllOfCatches.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SignalsAllOfCatches.prototype['name'] = undefined;

/**
 * @member {String} type
 */
SignalsAllOfCatches.prototype['type'] = undefined;






export default SignalsAllOfCatches;

