/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaskAssignmentsEditable model module.
 * @module model/TaskAssignmentsEditable
 * @version 1.0.0
 */
class TaskAssignmentsEditable {
    /**
     * Constructs a new <code>TaskAssignmentsEditable</code>.
     * @alias module:model/TaskAssignmentsEditable
     */
    constructor() { 
        
        TaskAssignmentsEditable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskAssignmentsEditable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskAssignmentsEditable} obj Optional instance to populate.
     * @return {module:model/TaskAssignmentsEditable} The populated <code>TaskAssignmentsEditable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskAssignmentsEditable();

            if (data.hasOwnProperty('process_id')) {
                obj['process_id'] = ApiClient.convertToType(data['process_id'], 'Number');
            }
            if (data.hasOwnProperty('process_task_id')) {
                obj['process_task_id'] = ApiClient.convertToType(data['process_task_id'], 'String');
            }
            if (data.hasOwnProperty('assignment_id')) {
                obj['assignment_id'] = ApiClient.convertToType(data['assignment_id'], 'Number');
            }
            if (data.hasOwnProperty('assignment_type')) {
                obj['assignment_type'] = ApiClient.convertToType(data['assignment_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} process_id
 */
TaskAssignmentsEditable.prototype['process_id'] = undefined;

/**
 * @member {String} process_task_id
 */
TaskAssignmentsEditable.prototype['process_task_id'] = undefined;

/**
 * @member {Number} assignment_id
 */
TaskAssignmentsEditable.prototype['assignment_id'] = undefined;

/**
 * @member {module:model/TaskAssignmentsEditable.AssignmentTypeEnum} assignment_type
 */
TaskAssignmentsEditable.prototype['assignment_type'] = undefined;





/**
 * Allowed values for the <code>assignment_type</code> property.
 * @enum {String}
 * @readonly
 */
TaskAssignmentsEditable['AssignmentTypeEnum'] = {

    /**
     * value: "ProcessMaker\\Models\\User"
     * @const
     */
    "User": "ProcessMaker\\Models\\User",

    /**
     * value: "ProcessMaker\\Models\\Group"
     * @const
     */
    "Group": "ProcessMaker\\Models\\Group"
};



export default TaskAssignmentsEditable;

