/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateUserGroups model module.
 * @module model/UpdateUserGroups
 * @version 1.0.0
 */
class UpdateUserGroups {
    /**
     * Constructs a new <code>UpdateUserGroups</code>.
     * Update a user&#39;s groups
     * @alias module:model/UpdateUserGroups
     */
    constructor() { 
        
        UpdateUserGroups.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateUserGroups</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUserGroups} obj Optional instance to populate.
     * @return {module:model/UpdateUserGroups} The populated <code>UpdateUserGroups</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserGroups();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} groups
 */
UpdateUserGroups.prototype['groups'] = undefined;






export default UpdateUserGroups;

