/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenClient from './TokenClient';

/**
 * The UserToken model module.
 * @module model/UserToken
 * @version 1.0.0
 */
class UserToken {
    /**
     * Constructs a new <code>UserToken</code>.
     * @alias module:model/UserToken
     */
    constructor() { 
        
        UserToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserToken} obj Optional instance to populate.
     * @return {module:model/UserToken} The populated <code>UserToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserToken();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], Object);
            }
            if (data.hasOwnProperty('revoked')) {
                obj['revoked'] = ApiClient.convertToType(data['revoked'], 'Boolean');
            }
            if (data.hasOwnProperty('client')) {
                obj['client'] = TokenClient.constructFromObject(data['client']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserToken.prototype['id'] = undefined;

/**
 * @member {Number} user_id
 */
UserToken.prototype['user_id'] = undefined;

/**
 * @member {Number} client_id
 */
UserToken.prototype['client_id'] = undefined;

/**
 * @member {String} name
 */
UserToken.prototype['name'] = undefined;

/**
 * @member {Object} scopes
 */
UserToken.prototype['scopes'] = undefined;

/**
 * @member {Boolean} revoked
 */
UserToken.prototype['revoked'] = undefined;

/**
 * @member {module:model/TokenClient} client
 */
UserToken.prototype['client'] = undefined;

/**
 * @member {Date} created_at
 */
UserToken.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
UserToken.prototype['updated_at'] = undefined;

/**
 * @member {Date} expires_at
 */
UserToken.prototype['expires_at'] = undefined;






export default UserToken;

