/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Media from './Media';
import UsersAllOf from './UsersAllOf';
import UsersEditable from './UsersEditable';

/**
 * The Users model module.
 * @module model/Users
 * @version 1.0.0
 */
class Users {
    /**
     * Constructs a new <code>Users</code>.
     * The attributes that are mass assignable.
     * @alias module:model/Users
     * @implements module:model/UsersAllOf
     * @implements module:model/UsersEditable
     */
    constructor() { 
        UsersAllOf.initialize(this);UsersEditable.initialize(this);
        Users.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Users</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Users} obj Optional instance to populate.
     * @return {module:model/Users} The populated <code>Users</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Users();
            UsersAllOf.constructFromObject(data, obj);
            UsersEditable.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('postal')) {
                obj['postal'] = ApiClient.convertToType(data['postal'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('fax')) {
                obj['fax'] = ApiClient.convertToType(data['fax'], 'String');
            }
            if (data.hasOwnProperty('cell')) {
                obj['cell'] = ApiClient.convertToType(data['cell'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('datetime_format')) {
                obj['datetime_format'] = ApiClient.convertToType(data['datetime_format'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('is_administrator')) {
                obj['is_administrator'] = ApiClient.convertToType(data['is_administrator'], 'Boolean');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('loggedin_at')) {
                obj['loggedin_at'] = ApiClient.convertToType(data['loggedin_at'], 'String');
            }
            if (data.hasOwnProperty('remember_token')) {
                obj['remember_token'] = ApiClient.convertToType(data['remember_token'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('fullname')) {
                obj['fullname'] = ApiClient.convertToType(data['fullname'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], [Media]);
            }
            if (data.hasOwnProperty('birthdate')) {
                obj['birthdate'] = ApiClient.convertToType(data['birthdate'], 'Date');
            }
            if (data.hasOwnProperty('delegation_user_id')) {
                obj['delegation_user_id'] = ApiClient.convertToType(data['delegation_user_id'], 'String');
            }
            if (data.hasOwnProperty('manager_id')) {
                obj['manager_id'] = ApiClient.convertToType(data['manager_id'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], {'String': Object});
            }
            if (data.hasOwnProperty('force_change_password')) {
                obj['force_change_password'] = ApiClient.convertToType(data['force_change_password'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Users.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
Users.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Users.prototype['updated_at'] = undefined;

/**
 * @member {Date} deleted_at
 */
Users.prototype['deleted_at'] = undefined;

/**
 * @member {String} email
 */
Users.prototype['email'] = undefined;

/**
 * @member {String} firstname
 */
Users.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
Users.prototype['lastname'] = undefined;

/**
 * @member {String} username
 */
Users.prototype['username'] = undefined;

/**
 * @member {String} password
 */
Users.prototype['password'] = undefined;

/**
 * @member {String} address
 */
Users.prototype['address'] = undefined;

/**
 * @member {String} city
 */
Users.prototype['city'] = undefined;

/**
 * @member {String} state
 */
Users.prototype['state'] = undefined;

/**
 * @member {String} postal
 */
Users.prototype['postal'] = undefined;

/**
 * @member {String} country
 */
Users.prototype['country'] = undefined;

/**
 * @member {String} phone
 */
Users.prototype['phone'] = undefined;

/**
 * @member {String} fax
 */
Users.prototype['fax'] = undefined;

/**
 * @member {String} cell
 */
Users.prototype['cell'] = undefined;

/**
 * @member {String} title
 */
Users.prototype['title'] = undefined;

/**
 * @member {String} timezone
 */
Users.prototype['timezone'] = undefined;

/**
 * @member {String} datetime_format
 */
Users.prototype['datetime_format'] = undefined;

/**
 * @member {String} language
 */
Users.prototype['language'] = undefined;

/**
 * @member {Boolean} is_administrator
 */
Users.prototype['is_administrator'] = undefined;

/**
 * @member {String} expires_at
 */
Users.prototype['expires_at'] = undefined;

/**
 * @member {String} loggedin_at
 */
Users.prototype['loggedin_at'] = undefined;

/**
 * @member {String} remember_token
 */
Users.prototype['remember_token'] = undefined;

/**
 * @member {module:model/Users.StatusEnum} status
 */
Users.prototype['status'] = undefined;

/**
 * @member {String} fullname
 */
Users.prototype['fullname'] = undefined;

/**
 * @member {String} avatar
 */
Users.prototype['avatar'] = undefined;

/**
 * @member {Array.<module:model/Media>} media
 */
Users.prototype['media'] = undefined;

/**
 * @member {Date} birthdate
 */
Users.prototype['birthdate'] = undefined;

/**
 * @member {String} delegation_user_id
 */
Users.prototype['delegation_user_id'] = undefined;

/**
 * @member {String} manager_id
 */
Users.prototype['manager_id'] = undefined;

/**
 * @member {Object.<String, Object>} meta
 */
Users.prototype['meta'] = undefined;

/**
 * @member {Boolean} force_change_password
 */
Users.prototype['force_change_password'] = undefined;


// Implement UsersAllOf interface:
/**
 * @member {Number} id
 */
UsersAllOf.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
UsersAllOf.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
UsersAllOf.prototype['updated_at'] = undefined;
/**
 * @member {Date} deleted_at
 */
UsersAllOf.prototype['deleted_at'] = undefined;
// Implement UsersEditable interface:
/**
 * @member {String} email
 */
UsersEditable.prototype['email'] = undefined;
/**
 * @member {String} firstname
 */
UsersEditable.prototype['firstname'] = undefined;
/**
 * @member {String} lastname
 */
UsersEditable.prototype['lastname'] = undefined;
/**
 * @member {String} username
 */
UsersEditable.prototype['username'] = undefined;
/**
 * @member {String} password
 */
UsersEditable.prototype['password'] = undefined;
/**
 * @member {String} address
 */
UsersEditable.prototype['address'] = undefined;
/**
 * @member {String} city
 */
UsersEditable.prototype['city'] = undefined;
/**
 * @member {String} state
 */
UsersEditable.prototype['state'] = undefined;
/**
 * @member {String} postal
 */
UsersEditable.prototype['postal'] = undefined;
/**
 * @member {String} country
 */
UsersEditable.prototype['country'] = undefined;
/**
 * @member {String} phone
 */
UsersEditable.prototype['phone'] = undefined;
/**
 * @member {String} fax
 */
UsersEditable.prototype['fax'] = undefined;
/**
 * @member {String} cell
 */
UsersEditable.prototype['cell'] = undefined;
/**
 * @member {String} title
 */
UsersEditable.prototype['title'] = undefined;
/**
 * @member {String} timezone
 */
UsersEditable.prototype['timezone'] = undefined;
/**
 * @member {String} datetime_format
 */
UsersEditable.prototype['datetime_format'] = undefined;
/**
 * @member {String} language
 */
UsersEditable.prototype['language'] = undefined;
/**
 * @member {Boolean} is_administrator
 */
UsersEditable.prototype['is_administrator'] = undefined;
/**
 * @member {String} expires_at
 */
UsersEditable.prototype['expires_at'] = undefined;
/**
 * @member {String} loggedin_at
 */
UsersEditable.prototype['loggedin_at'] = undefined;
/**
 * @member {String} remember_token
 */
UsersEditable.prototype['remember_token'] = undefined;
/**
 * @member {module:model/UsersEditable.StatusEnum} status
 */
UsersEditable.prototype['status'] = undefined;
/**
 * @member {String} fullname
 */
UsersEditable.prototype['fullname'] = undefined;
/**
 * @member {String} avatar
 */
UsersEditable.prototype['avatar'] = undefined;
/**
 * @member {Array.<module:model/Media>} media
 */
UsersEditable.prototype['media'] = undefined;
/**
 * @member {Date} birthdate
 */
UsersEditable.prototype['birthdate'] = undefined;
/**
 * @member {String} delegation_user_id
 */
UsersEditable.prototype['delegation_user_id'] = undefined;
/**
 * @member {String} manager_id
 */
UsersEditable.prototype['manager_id'] = undefined;
/**
 * @member {Object.<String, Object>} meta
 */
UsersEditable.prototype['meta'] = undefined;
/**
 * @member {Boolean} force_change_password
 */
UsersEditable.prototype['force_change_password'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Users['StatusEnum'] = {

    /**
     * value: "ACTIVE"
     * @const
     */
    "ACTIVE": "ACTIVE",

    /**
     * value: "INACTIVE"
     * @const
     */
    "INACTIVE": "INACTIVE",

    /**
     * value: "SCHEDULED"
     * @const
     */
    "SCHEDULED": "SCHEDULED",

    /**
     * value: "OUT_OF_OFFICE"
     * @const
     */
    "OUT_OF_OFFICE": "OUT_OF_OFFICE"
};



export default Users;

