/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject from '../model/InlineObject';
import Settings from '../model/Settings';

/**
* CssSettings service.
* @module api/CssSettingsApi
* @version 1.0.0
*/
export default class CssSettingsApi {

    /**
    * Constructs a new CssSettingsApi. 
    * @alias module:api/CssSettingsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the updateCssSetting operation.
     * @callback module:api/CssSettingsApi~updateCssSettingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Settings} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create or update a new setting
     * Create a new Settings css-override
     * @param {module:model/InlineObject} inlineObject 
     * @param {module:api/CssSettingsApi~updateCssSettingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Settings}
     */
    updateCssSetting(inlineObject, callback) {
      let postBody = inlineObject;
      // verify the required parameter 'inlineObject' is set
      if (inlineObject === undefined || inlineObject === null) {
        throw new Error("Missing the required parameter 'inlineObject' when calling updateCssSetting");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Settings;
      return this.apiClient.callApi(
        '/customize-ui', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
