/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineResponse20027 from '../model/InlineResponse20027';
import Signals from '../model/Signals';
import SignalsEditable from '../model/SignalsEditable';

/**
* Signals service.
* @module api/SignalsApi
* @version 1.0.0
*/
export default class SignalsApi {

    /**
    * Constructs a new SignalsApi. 
    * @alias module:api/SignalsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createSignal operation.
     * @callback module:api/SignalsApi~createSignalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Signals} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new Global Signal
     * Creates a new global signal
     * @param {module:model/SignalsEditable} signalsEditable 
     * @param {module:api/SignalsApi~createSignalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Signals}
     */
    createSignal(signalsEditable, callback) {
      let postBody = signalsEditable;
      // verify the required parameter 'signalsEditable' is set
      if (signalsEditable === undefined || signalsEditable === null) {
        throw new Error("Missing the required parameter 'signalsEditable' when calling createSignal");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Signals;
      return this.apiClient.callApi(
        '/signals', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSignal operation.
     * @callback module:api/SignalsApi~deleteSignalCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a signal
     * @param {String} signalId ID of signal to delete
     * @param {module:api/SignalsApi~deleteSignalCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteSignal(signalId, callback) {
      let postBody = null;
      // verify the required parameter 'signalId' is set
      if (signalId === undefined || signalId === null) {
        throw new Error("Missing the required parameter 'signalId' when calling deleteSignal");
      }

      let pathParams = {
        'signal_id': signalId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/signals/{signal_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSignals operation.
     * @callback module:api/SignalsApi~getSignalsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20027} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all signals
     * Display a listing of the resource.
     * @param {Object} opts Optional parameters
     * @param {String} opts.filter Filter results by string. Searches Name, Description, and Status. Status must match exactly. Others can be a substring.
     * @param {String} opts.orderBy Field to order results by
     * @param {module:model/String} opts.orderDirection  (default to 'asc')
     * @param {Number} opts.perPage 
     * @param {module:api/SignalsApi~getSignalsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20027}
     */
    getSignals(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'filter': opts['filter'],
        'order_by': opts['orderBy'],
        'order_direction': opts['orderDirection'],
        'per_page': opts['perPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20027;
      return this.apiClient.callApi(
        '/signals', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSignalsById operation.
     * @callback module:api/SignalsApi~getSignalsByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Signals} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a single signal by ID
     * Display the specified resource.
     * @param {String} signalId signal id
     * @param {module:api/SignalsApi~getSignalsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Signals}
     */
    getSignalsById(signalId, callback) {
      let postBody = null;
      // verify the required parameter 'signalId' is set
      if (signalId === undefined || signalId === null) {
        throw new Error("Missing the required parameter 'signalId' when calling getSignalsById");
      }

      let pathParams = {
        'signal_id': signalId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Signals;
      return this.apiClient.callApi(
        '/signals/{signal_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSignal operation.
     * @callback module:api/SignalsApi~updateSignalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Signals} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a signal
     * @param {String} signalId ID of signal to update
     * @param {module:model/SignalsEditable} signalsEditable 
     * @param {module:api/SignalsApi~updateSignalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Signals}
     */
    updateSignal(signalId, signalsEditable, callback) {
      let postBody = signalsEditable;
      // verify the required parameter 'signalId' is set
      if (signalId === undefined || signalId === null) {
        throw new Error("Missing the required parameter 'signalId' when calling updateSignal");
      }
      // verify the required parameter 'signalsEditable' is set
      if (signalsEditable === undefined || signalsEditable === null) {
        throw new Error("Missing the required parameter 'signalsEditable' when calling updateSignal");
      }

      let pathParams = {
        'signal_id': signalId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['pm_api_auth_code', 'pm_api_bearer', 'pm_api_key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Signals;
      return this.apiClient.callApi(
        '/signals/{signal_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
