/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.Media();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Media', function() {
    it('should create an instance of Media', function() {
      // uncomment below and update the code to test Media
      //var instane = new ProcessMakerApi.Media();
      //expect(instance).to.be.a(ProcessMakerApi.Media);
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property modelId (base name: "model_id")', function() {
      // uncomment below and update the code to test the property modelId
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property modelType (base name: "model_type")', function() {
      // uncomment below and update the code to test the property modelType
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property collectionName (base name: "collection_name")', function() {
      // uncomment below and update the code to test the property collectionName
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property fileName (base name: "file_name")', function() {
      // uncomment below and update the code to test the property fileName
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property mimeType (base name: "mime_type")', function() {
      // uncomment below and update the code to test the property mimeType
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property disk (base name: "disk")', function() {
      // uncomment below and update the code to test the property disk
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property manipulations (base name: "manipulations")', function() {
      // uncomment below and update the code to test the property manipulations
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property customProperties (base name: "custom_properties")', function() {
      // uncomment below and update the code to test the property customProperties
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property responsiveImages (base name: "responsive_images")', function() {
      // uncomment below and update the code to test the property responsiveImages
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

    it('should have the property orderColumn (base name: "order_column")', function() {
      // uncomment below and update the code to test the property orderColumn
      //var instance = new ProcessMakerApi.Media();
      //expect(instance).to.be();
    });

  });

}));
