/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.ProcessStartEvents();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessStartEvents', function() {
    it('should create an instance of ProcessStartEvents', function() {
      // uncomment below and update the code to test ProcessStartEvents
      //var instane = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be.a(ProcessMakerApi.ProcessStartEvents);
    });

    it('should have the property eventDefinitions (base name: "eventDefinitions")', function() {
      // uncomment below and update the code to test the property eventDefinitions
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

    it('should have the property parallelMultiple (base name: "parallelMultiple")', function() {
      // uncomment below and update the code to test the property parallelMultiple
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

    it('should have the property outgoing (base name: "outgoing")', function() {
      // uncomment below and update the code to test the property outgoing
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

    it('should have the property incoming (base name: "incoming")', function() {
      // uncomment below and update the code to test the property incoming
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ProcessMakerApi.ProcessStartEvents();
      //expect(instance).to.be();
    });

  });

}));
