/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.ProcessRequestEditable();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessRequestEditable', function() {
    it('should create an instance of ProcessRequestEditable', function() {
      // uncomment below and update the code to test ProcessRequestEditable
      //var instane = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be.a(ProcessMakerApi.ProcessRequestEditable);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property callableId (base name: "callable_id")', function() {
      // uncomment below and update the code to test the property callableId
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property processId (base name: "process_id")', function() {
      // uncomment below and update the code to test the property processId
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

    it('should have the property process (base name: "process")', function() {
      // uncomment below and update the code to test the property process
      //var instance = new ProcessMakerApi.ProcessRequestEditable();
      //expect(instance).to.be();
    });

  });

}));
