/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessRequestTokenAllOf', function() {
    it('should create an instance of ProcessRequestTokenAllOf', function() {
      // uncomment below and update the code to test ProcessRequestTokenAllOf
      //var instane = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be.a(ProcessMakerApi.ProcessRequestTokenAllOf);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property processId (base name: "process_id")', function() {
      // uncomment below and update the code to test the property processId
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property processRequestId (base name: "process_request_id")', function() {
      // uncomment below and update the code to test the property processRequestId
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property elementId (base name: "element_id")', function() {
      // uncomment below and update the code to test the property elementId
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property elementType (base name: "element_type")', function() {
      // uncomment below and update the code to test the property elementType
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property elementIndex (base name: "element_index")', function() {
      // uncomment below and update the code to test the property elementIndex
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property elementName (base name: "element_name")', function() {
      // uncomment below and update the code to test the property elementName
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property initiatedAt (base name: "initiated_at")', function() {
      // uncomment below and update the code to test the property initiatedAt
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property advanceStatus (base name: "advanceStatus")', function() {
      // uncomment below and update the code to test the property advanceStatus
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property dueNotified (base name: "due_notified")', function() {
      // uncomment below and update the code to test the property dueNotified
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property process (base name: "process")', function() {
      // uncomment below and update the code to test the property process
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

    it('should have the property processRequest (base name: "process_request")', function() {
      // uncomment below and update the code to test the property processRequest
      //var instance = new ProcessMakerApi.ProcessRequestTokenAllOf();
      //expect(instance).to.be();
    });

  });

}));
