/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.ScreensEditable();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScreensEditable', function() {
    it('should create an instance of ScreensEditable', function() {
      // uncomment below and update the code to test ScreensEditable
      //var instane = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be.a(ProcessMakerApi.ScreensEditable);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property config (base name: "config")', function() {
      // uncomment below and update the code to test the property config
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property computed (base name: "computed")', function() {
      // uncomment below and update the code to test the property computed
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property watchers (base name: "watchers")', function() {
      // uncomment below and update the code to test the property watchers
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property customCss (base name: "custom_css")', function() {
      // uncomment below and update the code to test the property customCss
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

    it('should have the property screenCategoryId (base name: "screen_category_id")', function() {
      // uncomment below and update the code to test the property screenCategoryId
      //var instance = new ProcessMakerApi.ScreensEditable();
      //expect(instance).to.be();
    });

  });

}));
