/**
 * ProcessMaker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@processmaker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProcessMakerApi);
  }
}(this, function(expect, ProcessMakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProcessMakerApi.RebuildScriptExecutorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RebuildScriptExecutorsApi', function() {
    describe('cancelScriptExecutor', function() {
      it('should call cancelScriptExecutor successfully', function(done) {
        //uncomment below and update the code to test cancelScriptExecutor
        //instance.cancelScriptExecutor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createScriptExecutor', function() {
      it('should call createScriptExecutor successfully', function(done) {
        //uncomment below and update the code to test createScriptExecutor
        //instance.createScriptExecutor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteScriptExecutor', function() {
      it('should call deleteScriptExecutor successfully', function(done) {
        //uncomment below and update the code to test deleteScriptExecutor
        //instance.deleteScriptExecutor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAvailableLanguages', function() {
      it('should call getAvailableLanguages successfully', function(done) {
        //uncomment below and update the code to test getAvailableLanguages
        //instance.getAvailableLanguages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getScriptExecutors', function() {
      it('should call getScriptExecutors successfully', function(done) {
        //uncomment below and update the code to test getScriptExecutors
        //instance.getScriptExecutors(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateScriptExecutor', function() {
      it('should call updateScriptExecutor successfully', function(done) {
        //uncomment below and update the code to test updateScriptExecutor
        //instance.updateScriptExecutor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
